create table asset (created_at timestamp(6), delivery_job_id bigint not null, id bigserial not null, phelix_asset_id bigint, phelix_asset_version bigint, updated_at timestamp(6), created_by varchar(255), local_path varchar(255), modified_by varchar(255), path varchar(255), storage_id varchar(255), primary key (id));
create table connection (created_at timestamp(6), id bigserial not null, updated_at timestamp(6), created_by varchar(255), description varchar(255), modified_by varchar(255), name varchar(255), type varchar(255), config jsonb, primary key (id));
create table contact (created_at timestamp(6), id bigserial not null, updated_at timestamp(6), created_by varchar(255), email varchar(255) unique, first_name varchar(255), last_name varchar(255), modified_by varchar(255), primary key (id));
create table delivery_job (last_reported_progress float(53), progress float(53), created_at timestamp(6), id bigserial not null, profile_id bigint, updated_at timestamp(6), created_by varchar(255), external_id varchar(255), initiator varchar(255), modified_by varchar(255), status varchar(255), transfer_info jsonb, primary key (id));
create table profile (connection_id bigint, created_at timestamp(6), id bigserial not null, updated_at timestamp(6), created_by varchar(255), description varchar(255), modified_by varchar(255), name varchar(255), root_path varchar(255), primary key (id));
create table profile_completion_bcc_contacts (completion_bcc_contacts_id bigint not null, profile_id bigint not null, primary key (completion_bcc_contacts_id, profile_id));
create table profile_completion_cc_contacts (completion_cc_contacts_id bigint not null, profile_id bigint not null, primary key (completion_cc_contacts_id, profile_id));
create table profile_completion_contacts (completion_contacts_id bigint not null, profile_id bigint not null, primary key (completion_contacts_id, profile_id));
create table profile_failure_contacts (failure_contacts_id bigint not null, profile_id bigint not null, primary key (failure_contacts_id, profile_id));
create table shedlock (lock_until timestamp(6), locked_at timestamp(6), locked_by varchar(255), name varchar(255) not null, primary key (name));
create table storage (created_at timestamp(6), id bigserial not null, updated_at timestamp(6), created_by varchar(255), location varchar(255), modified_by varchar(255), name varchar(255), storage_id varchar(255), type varchar(255), attributes jsonb, primary key (id));
alter table if exists asset add constraint FK8oua4hy9hh4rmdpjt68g59ytu foreign key (delivery_job_id) references delivery_job;
alter table if exists delivery_job add constraint FKpubehbr7pcpgyy6w44l40sidy foreign key (profile_id) references profile;
alter table if exists profile add constraint FKebm44mfaqgjna4b4tqixedc1w foreign key (connection_id) references connection;
alter table if exists profile_completion_bcc_contacts add constraint FKpsyqy6e3i7eneia5og9g6pep0 foreign key (completion_bcc_contacts_id) references contact;
alter table if exists profile_completion_bcc_contacts add constraint FKccor9ws2thuqg0nwrtoy9ck8q foreign key (profile_id) references profile;
alter table if exists profile_completion_cc_contacts add constraint FK5ca7ivmct5hn64788g99ujq43 foreign key (completion_cc_contacts_id) references contact;
alter table if exists profile_completion_cc_contacts add constraint FKmifldins6ovd3rc8n57hmpndv foreign key (profile_id) references profile;
alter table if exists profile_completion_contacts add constraint FKj19cdvku5tq5q0e1wjqb6u1bt foreign key (completion_contacts_id) references contact;
alter table if exists profile_completion_contacts add constraint FK91byweemnb7w49kgiwp42f56b foreign key (profile_id) references profile;
alter table if exists profile_failure_contacts add constraint FKev7tngdwj3xqemnvmqavt2mnm foreign key (failure_contacts_id) references contact;
alter table if exists profile_failure_contacts add constraint FKasabfliprfa3amktcxodpf8u1 foreign key (profile_id) references profile;